trigger:
  tags:
    include:
      - v*.*

stages:
  - stage: onPush
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
    jobs:
      - job: onPushJob
        pool:
          vmImage: "ubuntu-20.04"

        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python 3.9"
            inputs:
              versionSpec: "3.9"

          - script: |
              python3 -m pip install --upgrade pip
              pip install -r unit-requirements.txt
            displayName: "Install dependencies"

          - script: |
              python3 -m build --wheel
            displayName: "Build Package"

          - task: TwineAuthenticate@1
            displayName: Twine Authenticate
            inputs:
              artifactFeed: reusabilityLab/reusabilityLab-packages

          - script: |
              python -m twine upload -r reusabilityLab-packages--config-file $(PYPIRC_PATH) dist/*.whl
            displayName: "Upload to Azure Artifacts"
